doctrine:
  dbal:
    driver: 'pdo_mysql'
    server_version: '5.7'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
    url: '%env(resolve:DATABASE_URL)%'
    types:
      currency: App\Doctrine\Type\CurrencyType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      Money:
        type: xml
        prefix: Money
        dir: "%kernel.project_dir%/config/doctrine/Money"
        is_bundle: false
      Entity:
        type: xml
        prefix: App\Entity
        dir: "%kernel.project_dir%/config/doctrine/Entity"
        is_bundle: false
      Security:
        type: xml
        prefix: App\Entity\Security
        dir: "%kernel.project_dir%/config/doctrine/Entity/Security"
        is_bundle: false
