flysystem:
    storages:
        public:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public'
        images:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images'
