fos_rest:
  body_listener:
    enabled: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }
  view:
    formats:
      json: true
      xml: false
      jsonp: false
      rss: false
      html: false
    view_response_listener: 'force'
