vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        images:
            uri_prefix: /images
            upload_destination: images
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
