App\Entity\Product:
  properties:
    name:
      - Regex: /^[\w\s\+]+/
      - Type: string
      - Length:
          min: 3
          max: 255
      - NotBlank:
          groups:
            - Create
    price:
      - NotNull:
          groups: Create
      - App\Validator\Money\GreaterThan:
          value: 0
      - App\Validator\Currency\Choice:
            choices:
              - USD
App\Entity\Image:
  properties:
    file:
      - Image: ~

App\DTO\Product\ProductCriteria:
  properties:
    name:
      - Type: string
      - Length:
          max: 125

App\DTO\Purchase:
  properties:
    product:
      - NotNull: ~
    quantity:
      - NotNull: ~
      - Type: integer
      - GreaterThan: 0

App\Entity\Money:
  properties:
    amount:
      - GreaterThan: 0
    currency:
      - Length:
          min: 3
          max: 3
