parameters:
  domain: 'http://localhost:81'
  locale: '%env(APP_LOCALE)%'
  image.filter.webp: 'images'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $locale: '%locale%'
      $gitHooksOriginDir: '%kernel.project_dir%/hooks'
      $gitHooksTargetDir: '%kernel.project_dir%/.git/hooks'

  # https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1768
  sensio_framework_extra.view.listener:
    alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

  App\Pricing\StrategyInterface: '@App\Service\Pricing\PricingStrategy'
  App\Money\MathInterface: '@App\Service\Money\MoneyMath'

  App\Controller\:
    resource: ../src/Controller
    tags: [ controller.service_arguments ]

  App\Service\:
    resource: ../src/Service

  App\Service\Serializer\Handler\:
    resource: ../src/Service/Serializer/Handler
    tags: [ "jms_serializer.subscribing_handler" ]

  App\Security\Voter\:
    resource: ../src/Security/Voter

  App\Form\Type\:
    resource: ../src/Form/Type
    tags: [ "form.type" ]

  App\ArgumentResolver\:
    resource: ../src/ArgumentResolver
    tags:
      - { name: "controller.argument_value_resolver", priority: 50 }

  App\Command\:
    resource: ../src/Command
    tags: [ "console.command" ]

  App\EventSubscriber\:
    resource: ../src/EventSubscriber
    tags: [ "kernel.event_subscriber" ]

  App\Form\DataTransformer\:
    resource: ../src/Form/DataTransformer

  App\Repository\:
    resource: ../src/Repository

  App\Service\Image\UploadImage:
      bind:
        $filter: '@liip_imagine.service.filter'
        $filterSet: '%image.filter.webp%'

