App\Model\Pricing\Receipt\Item:
  exclusion_policy: ALL
  properties:
    productName:
      expose: true
      serialized_name: name
    quantity:
      expose: true
    unitPrice:
      expose: true
      serialized_name: price
    grandTotal:
      expose: true
      serialized_name: total